export const cafeData = [
  {
    id: 1,
    image: require("../assets/images/Image.png"),
    name: "Peek-a-boo",
    cuisine: "Азтиатская кухня",
    city: 'Astana',
    rating: 8,
    isPopular: true,
    isFamilyFriendly: false,
  },
  {
    id: 2,
    image: require("../assets/images/Image.png"),
    name: "Pepper Onion",
    cuisine: "Итальянская кухня",
    city: 'Astana',
    rating: 4,
    isPopular: false,
    isFamilyFriendly: true,
  },
  {
    id: 3,
    image: require("../assets/images/Image.png"),
    name: "Koreana",
    cuisine: "Азтиатская кухня",
    rating: 10,
    city: 'Almaty',
    isPopular: true,
    isFamilyFriendly: true,
  },
  {
    id: 4,
    image: require("../assets/images/Image.png"),
    name: "Rainblow",
    cuisine: "Французская кухня",
    rating: 3,
    city: 'Almaty',
    isPopular: false,
    isFamilyFriendly: false,
  },
];
