export const cafeData = [
  {
    id: 1,
    image: require("../assets/images/Image.png"),
    name: "Peek-a-boo",
    cuisine: "Высокий рейтинг",
    category: "Высокий рейтинг",
    city: 'Astana',
    rating: 8,
  },
  {
    id: 2,
    image: require("../assets/images/Image.png"),
    name: "Pepper Onion",
    cuisine: "Итальянская",
    category: "Итальянская",
    city: 'Astana',
    rating: 4,
  },
  {
    id: 3,
    image: require("../assets/images/Image.png"),
    name: "Koreana",
    cuisine: "",
    category: "Популярные",
    rating: 10,
    city: 'Almaty',
  },
  {
    id: 4,
    image: require("../assets/images/Image.png"),
    name: "Rainblow",
    cuisine: "Французская",
    category: "Французская",
    rating: 3,
    city: 'Almaty',
  },
  {
    id: 5,
    image: require("../assets/images/Image.png"),
    name: "Rainblow",
    cuisine: "Семейные",
    category: "Семейные",
    rating: 3,
    city: 'Almaty',
  },
];
